apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name:  tmf-apis-system
  description: TMF APIs
  annotations:
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://www.tmforum.org
      title: TM Forum
      icon: https://www.tmforum.org/wp-content/themes/pro-child/framework/img/logo/TMForum_logo_2021.svg
spec:
  owner: default-team