apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name:  tmf-apis-system
  description: TMF APIs
  annotations:
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://www.tmforum.org
      title: TM Forum
spec:
  owner: default-team