apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tmf-product-catalog-management-api
  description: API for Product Catalog Management
spec:
  type: openapi
  lifecycle: experimental
  owner: default-team
  definition:
    $text: ../../../src/main/resources/openapi.yaml